Repository TamtamHero/fw-fanctrl, pull requests merged in 2024-08, with the labels that each got.

#63 fixing missing print for command execution
  fanctrl.py
Labels: bug

#61 Update to main branch + switch to fw-ectool
  README.md
  fanctrl.py
  nix/module.nix
  nix/packages/fw-fanctrl.nix
Labels: enhancement, packaging/nix

#64 small unix socket changes
  fanctrl.py
Labels: bug, enhancement

#65 README.md documentation update
  .github/ISSUE_TEMPLATE/bug-report---packaging-windows.md
  README.md
  fanctrl.py
Labels: documentation

#66 Command arguments refactoring Pt.1
  README.md
  fanctrl.py
  services/fw-fanctrl.service
  services/system-sleep/fw-fanctrl-suspend
Labels: documentation, enhancement

#69 add no battery mode for mainboards without battery
  README.md
  fanctrl.py
  install.sh
  services/fw-fanctrl.service
Labels: enhancement

#70 adding ectool sub-dependency to documentation
  README.md
Labels: documentation

#75 Add ToC + link to NixOS Documentation
  README.md
  doc/README.md
  doc/commands.md
  doc/configuration.md
Labels: documentation

#78 Add choice to print fan speed percentage
  doc/commands.md
  fanctrl.py
Labels: enhancement
